import:
  phones:
    - name: Samsung Galaxy S9
      count: 1
    - name: Samsung Galaxy S8
      count: 2
    - name: Motorola Nexus 6
      count: 1
    - name: Oneplus 9
      count: 1
    - name: Apple iPhone 13
      count: 1
    - name: Apple iPhone 12
      count: 1
    - name: Apple iPhone 11
      count: 1
    - name: iPhone X
      count: 1
    - name: Nokia 3310
      count: 1
