/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package io.bookphone.web.api

import io.bookphone.web.api.model.PhoneDetailsResponseDto
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*

import kotlinx.coroutines.flow.Flow

@RequestMapping("\${api.base-path:/api/v1}")
interface PhoneApi {

    fun getDelegate(): PhoneApiDelegate = object : PhoneApiDelegate {}

    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/phone/{phoneId}"],
            produces = ["application/json"]
    )
    suspend fun getPhoneDetails(@PathVariable("phoneId") phoneId: kotlin.String
): ResponseEntity<PhoneDetailsResponseDto> {
        return getDelegate().getPhoneDetails(phoneId)
    }

    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/phone"],
            produces = ["application/json"]
    )
    suspend fun getPhones(@RequestParam(value = "limit", required = false) limit: kotlin.Int?, @RequestParam(value = "offset", required = false) offset: kotlin.Int?
): ResponseEntity<Flow<PhoneDetailsResponseDto>> {
        return getDelegate().getPhones(limit, offset)
    }
}
